name: EAS Build APK

on:
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install EAS CLI
        run: npm install -g eas-cli

      - name: Install dependencies
        run: npm install

      - name: Run EAS Build (Preview APK)
        env:
          EXPO_TOKEN: ${{ secrets.EAS_TOKEN }}
        run: eas build -p android --profile preview --non-interactive
